version: '3'
services:
  db:
    image: postgres:latest
    container_name: local-postgres-fast-campus
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastcampus_db

    volumes:
      - /home/raygbrn/FastCampus/fastcampus_postgres/db
